export const POST_QUESTION_REQUEST = 'POST_QUESTION_REQUEST';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAILURE = 'POST_QUESTION_FAILURE';

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE';

export const GET_USER_DOUBT_REQUEST =  'GET_USER_DOUBT_REQUEST';
export const GET_USER_DOUBT_SUCCESS =  'GET_USER_DOUBT_SUCCESS';
export const GET_USER_DOUBT_FAILURE =  'GET_USER_DOUBT_FAILURE';

