export const Language = [
  "English",
  "Spanish",
  "Hindi",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Japanese",
  "Chinese",
];

export const Expertise = [
  "React.js",
  "Node.js",
  "English Literature",
  "Spanish Literature",
  "Hindi Literature",
  "Social Science",
  "Maths",
  "HTML",
  "CSS",
  "Physics",
  "Chemistry",
  "Directed Research",
  "Indirect Taxes",
  "Biology",
  "Basic Computer Science",
  "Sanskrit",
  "Business Management",
  "Economics",
  "Accounts",
];

